# Generated by Django 2.1.2 on 2018-10-23 10:35

import Graph.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('graph_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('file', models.FileField(upload_to=Graph.models.upload_location)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=30)),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Graph.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('node_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=30)),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Graph.Group')),
            ],
        ),
    ]
