# Generated by Django 2.1.2 on 2018-10-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Graph', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graph',
            name='graph_id',
        ),
        migrations.AddField(
            model_name='graph',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
