# Generated by Django 2.1.2 on 2018-10-23 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Graph', '0002_auto_20181023_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
