# Generated by Django 2.1.2 on 2018-10-23 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Graph', '0003_graph_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='graph',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Graph.Graph'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='node',
            name='graph',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Graph.Graph'),
            preserve_default=False,
        ),
    ]
