# Generated by Django 2.1.2 on 2018-10-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Graph', '0009_auto_20181024_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='node',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
