# Generated by Django 2.1.2 on 2018-10-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Graph', '0010_auto_20181024_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='id',
        ),
        migrations.RemoveField(
            model_name='node',
            name='id',
        ),
        migrations.AddField(
            model_name='group',
            name='id_in_db',
            field=models.AutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='node',
            name='id_in_db',
            field=models.AutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
